### ISSUE TITLE
Missing  mappwidget_1.2.0.jar???

### ISSUE THREAD

**Issue by Loshmag** [lemberg/mappwidget#10]
Hello, In the mappWidget's User Manual a library not available in GITHUB is used: mappwidget_1.2.0.jar.... How can i get it???

Thanks in advance...

**Comment by JavaMachine** [comment]
If you are using Android Studio, please import "mappwidgetlib" folder as Module into your project...
and in "app/build.gradle" add "compile project(':mappwidgetlib')" inside "dependencies { }"

**Comment by dbarysk** [comment]
We now have compiled jars in bin folder. Will update tutorial later. Jars can be found here https://github.com/lemberg/mappwidget/tree/master/bin
