### ISSUE TITLE
mAppWidget_1.2.0.jar missing

### ISSUE THREAD

**Issue by jdomingo88** [lemberg/mappwidget#11]
I want to work with mAppWidget API and I need jar file because I develop with Eclipse and it could be better for follow the user guide you've posted because it explains through an easy way to integrate this code library with an Android project.

**Comment by dbarysk** [comment]
We now have compiled jars in bin folder. Will update tutorial later. Jars can be found here https://github.com/lemberg/mappwidget/tree/master/bin
