### ISSUE TITLE
Integrate mappWidget to Android Studio project

### ISSUE THREAD

**Issue by suroviak** [lemberg/mappwidget#5]
Can you help me with integrate this library to android studio project. I try it with your user guide: http://lemberg.github.io/mappwidget/user_guide.html but i did not found mappwidget_1.2.0.jar. Next i try use it like plugin, but it is not work. 
Thank you

**Comment by ghost** [comment]
I solved it. 
You can copy the folder named 'mappwidgetlib' into your project folder. Then you should edit the build.gradle file in your developing module.
In dependencies scope, add code line like:
    dependencies {
        compile project(':mappwidgetlib')
    }
then it works. try it.

**Comment by suroviak** [comment]
Thank you.
And one more question. Where i can find online slice tool, that is mention here: http://lemberg.github.io/mappwidget/. Step 2.

**Comment by ghost** [comment]
Here: https://github.com/lemberg/mappwidget
In slicingtool folder. Import it into eclipse (Kepler edition), and run it as Eclipse Appliction.
In the new window, you can use the tool.

**Comment by mandalanil** [comment]
i am very new in programming so please kindly explain me step by step process using mappwidget library in android studio like http://lemberg.github.io/mappwidget/user_guide.html
